# Generated by Django 2.2.12 on 2020-04-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asana_app', '0002_auto_20200401_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='gid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='gid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
