# Generated by Django 2.2.12 on 2020-04-01 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asana_app', '0003_auto_20200401_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.TextField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='sections',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='asana_app.Sections'),
            preserve_default=False,
        ),
    ]
